const DataBook = [
  {
    image: "public/book/book-1.png",
    title: "How to Win Friends & Influence People",
    author: "Dale Carnegie",
    category: "self-imporovment",
    mybook: true,
    isRecommended: true,
  },
  {
    image: "public/book/book-2.png",
    title: "MBA",
    author: "Jason Barron",
    category: "econimic",
    mybook: true,
    isRecommended: true,
  },
  {
    image: "public/book/book-3.png",
    title: "The Intelligent Investor",
    author: "Benjamin Graham",
    category: "econimic",
    mybook: true,
    isRecommended: true,
  },
  {
    image: "public/book/book-4.png",
    title: "Great At Work",
    author: "Morten T.Hansen",
    category: "self-imporovment",
    mybook: true,
    isRecommended: true,
  },
  {
    image: "public/book/book-5.png",
    title: "You Do You",
    author: "Fellexandra Ruby",
    category: "self-imporovment",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-6.png",
    title: "Ikigai",
    author: "Hector Garcia & Frances...",
    category: "self-imporovment",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-7.png",
    title: "How To Be A Stoic",
    author: "Massimo Pigliucci",
    category: "self-imporovment",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-8.png",
    title: "The Subtle Not Giving A F*ck",
    author: "Mark Manson",
    category: "self-imporovment",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-9.png",
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    category: "novel",
    year: "1954",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-10.png",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "novel",
    year: "1960",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-11.png",
    title: "1984",
    author: "George Orwell",
    category: "novel",
    year: "1949",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-12.png",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "novel",
    year: "1925",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-13.png",
    title: "One Hundred Years of Solitude",
    author: "Gabriel Garcia Marquez",
    category: "novel",
    year: "1967",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-14.png",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    category: "novel",
    year: "1813",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-15.png",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    category: "novel",
    year: "1951",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-16.png",
    title: "The Kite Runner",
    author: " Khaled Hosseini",
    category: "novel",
    year: "1951",
    mybook: true,
    isRecommended: false,
  },
];

export default DataBook;
