const DataBook = [
  {
    image: "public/book/book-1.png",
    title: "How to Win Friends & Influence People",
    author: "Dale Carnegie",
    category: "self-imporovment",
    year: "1936",
    mybook: true,
    isRecommended: true,
  },
  {
    image: "public/book/book-2.png",
    title: "MBA",
    author: "Jason Barron",
    category: "econimic",
    year: "2019",
    mybook: true,
    isRecommended: true,
  },
  {
    image: "public/book/book-3.png",
    title: "The Intelligent Investor",
    author: "Benjamin Graham",
    category: "econimic",
    year: "1949",
    mybook: true,
    isRecommended: true,
  },
  {
    image: "public/book/book-4.png",
    title: "Great At Work",
    author: "Morten T.Hansen",
    category: "self-imporovment",
    year: "2018",
    mybook: true,
    isRecommended: true,
  },
  {
    image: "public/book/book-5.png",
    title: "You Do You",
    author: "Fellexandra Ruby",
    category: "self-imporovment",
    year: "2017",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-6.png",
    title: "Ikigai",
    author: "Hector Garcia & Frances...",
    category: "self-imporovment",
    year: "2016",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-7.png",
    title: "How To Be A Stoic",
    author: "Massimo Pigliucci",
    category: "self-imporovment",
    year: "2017",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-8.png",
    title: "The Subtle Not Giving A F*ck",
    author: "Mark Manson",
    category: "self-imporovment",
    year: "2016",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-9.jpg",
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    category: "novel",
    year: "1954",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-10.jpg",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "novel",
    year: "1960",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-11.jpg",
    title: "1984",
    author: "George Orwell",
    category: "novel",
    year: "1949",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-12.jpg",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "novel",
    year: "1925",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-13.jpg",
    title: "One Hundred Years of Solitude",
    author: "Gabriel Garcia Marquez",
    category: "novel",
    year: "1967",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-14.jpg",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    category: "novel",
    year: "1813",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-15.jpg",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    category: "novel",
    year: "1951",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-16.jpg",
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    category: "novel",
    year: "2003",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-17.jpg",
    title: "Capital in the Twenty-First Century",
    author: "Thomas Piketty",
    category: "economic",
    year: "2013",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-18.jpg",
    title:
      "Freakonomics: A Rogue Economist Explores the Hidden Side of Everything",
    author: "Steven D. Levitt dan Stephen J. Dubner",
    category: "economic",
    year: "2005",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-19.jpg",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    category: "economic",
    year: "2019",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-20.jpg",
    title: "The Big Short: Inside the Doomsday Machine",
    author: "Michael Lewis",
    category: "economic",
    year: "2010",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-21.jpg",
    title: "Nudge: Improving Decisions About Health, Wealth, and Happiness",
    author: "Richard H. Thaler dan Cass R. Sunstein",
    category: "economic",
    year: "2009",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-22.jpg",
    title:
      "Poor Economics: A Radical Rethinking of the Way to Fight Global Poverty",
    author: "Abhijit V. Banerjee dan Esther Duflo",
    category: "economic",
    year: "2012",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-23.jpg",
    title: "The Wealth of Nations",
    author: "Adam Smith",
    category: "economic",
    year: "1776",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-24.jpg",
    title: "Free to Choose: A Personal Statement",
    author: "Milton Friedman dan Rose D. Friedman",
    category: "economic",
    year: "1980",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-25.jpg",
    title: "The Element: How Finding Your Passion Changes Everything",
    author: "Sir Ken Robinson",
    category: "education",
    year: "2009",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-26.jpg",
    title: "Mindset: The New Psychology of Success",
    author: "Carol S. Dweck",
    category: "education",
    year: "2006",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-27.jpg",
    title: "Make It Stick: The Science of Successful Learning",
    author: "Peter C. Brown, Henry L. Roediger III, dan Mark A. McDaniel",
    category: "education",
    year: "2014",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-28.jpg",
    title: "The Smartest Kids in the World: And How They Got That Way",
    author: "Amanda Ripley",
    category: "education",
    year: "2014",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-29.jpg",
    title:
      "How Children Succeed: Grit, Curiosity, and the Hidden Power of Character",
    author: "Paul Tough",
    category: "education",
    year: "2013",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-30.jpg",
    title:
      "The Courage to Teach: Exploring the Inner Landscape of a Teacher's Life",
    author: "Parker J. Palmer",
    category: "education",
    year: "2007",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-31.jpg",
    title: "Educated: A Memoir",
    author: "Tara Westover",
    category: "education",
    year: "2018",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-32.jpg",
    title:
      "Teach Like a Champion: 49 Techniques that Put Students on the Path to College",
    author: "Doug Lemov",
    category: "education",
    year: "2008",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-33.jpg",
    title: "Where the Wild Things Are",
    author: "Maurice Sendak",
    category: "for-kids",
    year: "1984",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-34.jpg",
    title: "The Very Hungry Caterpillar",
    author: "Eric Carle",
    category: "for-kids",
    year: "1984",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-35.jpg",
    title: "Matilda",
    author: "Roald Dahl",
    category: "for-kids",
    year: "1988",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-36.jpg",
    title: "Charlotte's Web",
    author: "E.B. White",
    category: "for-kids",
    year: "2015",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-37.jpg",
    title: "Harry Potter and the Sorcerer'sStone",
    author: "J.K. Rowling",
    category: "for-kids",
    year: "1997",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-38.jpg",
    title: "Green Eggs and Ham",
    author: "Dr. Seuss",
    category: "for-kids",
    year: "1960",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-39.jpg",
    title: "The Gruffalo",
    author: "Julia Donaldson",
    category: "for-kids",
    year: "2005",
    mybook: true,
    isRecommended: false,
  },
  {
    image: "public/book/book-40.jpg",
    title: "The Cat in the Hat",
    author: "Dr. Seuss",
    category: "for-kids",
    year: "1957",
    mybook: true,
    isRecommended: false,
  },
];

export default DataBook;
